### /resources/application-mysql.yml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf8 # 예시입니다
    username: root # 예시입니다
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver