cloud:
  aws:
    credentials:
      accessKey: AKIARNB57U34RUK7J3ID       # AWS IAM AccessKey 적기
      secretKey: c49BsMh6zxJTZIEUG87Y3oUWmeOqd0rrDve6n6qE   # AWS IAM SecretKey 적기
    s3:
      bucket: helloworld4204    # ex) marryting-gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false